# Generated by Django 6.0.5 on 2026-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_email_alter_record_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
