# Generated by Django 6.0.5 on 2026-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(default='15', max_length=15),
            preserve_default=False,
        ),
    ]
